# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbud', '0002_auto_20161112_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='brand_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meals',
            name='brand_name',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='meals',
            name='category',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='meals',
            name='item_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='meals',
            name='item_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meals',
            name='item_name',
            field=models.CharField(max_length=80),
        ),
    ]
