# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbud', '0003_auto_20161112_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='brand_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='brand_name',
            field=models.CharField(max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='category',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='item_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='item_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='item_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
